name: Smart Contract Compilation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:

    - name: Compile smart contracts
      run: move build --path move/sources